Changed the file JS
ArtemKhoroshavin/Homework1 pull request #2
Opened 2023-06-25 22:36 UTC by ArtemKhoroshavin

Прошу проверить ДЗ.

2023-06-26 15:47 UTC, Mielilon requested changes
Хорошее решение, однако требуется внести некоторые доработки. 
Буду ждать обновление! Новую ветку создавать не нужно, просто запушьте исправления.

2023-06-26 15:47 UTC, Mielilon commented on hm-2.js
> +let userName = 'Брендан Эйх';
Тут более уместным будет использование `const`, так как автор (как и дата) не предполагает своего изменения.

2023-06-26 15:47 UTC, Mielilon commented on hm-2.js
> +num +=1;
Для тех моментов, когда нужно прибавить/вычесть единицу, стоит использовать еще более сокращающее сокращение :)

Выглядит оно так:
`num++;
num--;`

Такой формат можно часто встретить в реальных проектах.

2023-06-26 15:47 UTC, Mielilon commented on hm-2.js
> +    isAdmin: 'true',
Сейчас булево значение `true` является строкой. Нужно убрать кавычки, чтобы оно приняло соответствующее значение.

2023-06-26 15:47 UTC, Mielilon commented on hm-2.js
> +let user[city of residence] = 'Moscow'
Затерялись кавычки. Если мы хотим обратиться к свойству, у которого есть пробелы, нужно сделать так:
`user["city of residence"]`

Также let для объявления свойства неуместен. Его нужно просто убрать.

2023-06-26 15:47 UTC, mielilon commented on hm-2.js
> +let age = 20;
Так создается отдельная переменная, но при этом не изменяется свойство. Чтобы поменять значение свойства, нужно к нему обратиться через объект и присвоить новое значение.

2023-06-26 17:56 UTC, ArtemKhoroshavin commented on hm-2.js
> +num +=1;
Здравствуйте. Вот это задание я вообще не могу понять, я над своим то вариантом 1.5 часа ломал голову, я не понимаю, как это должно выглядеть в конечном итоге.

2023-06-26 18:38 UTC, ArtemKhoroshavin commented on hm-2.js
> +num +=1;
Я не уверен, что я разобрался до конца, просто методом "тыка"))
Это должно выглядеть так?
let num = 1;
num += 5;
num -= 3;
num *= 7;
num /= 3;
num++;
num--;
alert(num);

2023-06-27 17:36 UTC, Mielilon commented on hm-2.js
> +delete user[city of residence] = 'Moscow';
Нужно добавить кавычки, как в решении 9.1

2023-06-27 19:55 UTC, ArtemKhoroshavin commented on hm-2.js
> +delete user[city of residence] = 'Moscow';
спасибо, принято

2023-06-27 19:58 UTC, merged